import path from 'path';
import os from 'os';

export const ZEPHER_DIR = '.zepher';
export const GLOBAL_ZEPHER_DIR = path.join(os.homedir(), '.zepher');

export const CONFIG_FILE = 'config.yaml';
export const MEMORY_DIR = 'memory';
export const DECISIONS_DIR = 'decisions';
export const TASKS_DIR = 'tasks';
export const SESSIONS_DIR = 'sessions';
export const HANDOFFS_DIR = 'handoffs';
export const CONTEXT_DIR = 'context';
export const RESEARCH_DIR = 'research';
export const LOCAL_DIR = 'local';
export const SKILLS_DIR = 'skills';
export const RULES_DIR = 'rules';
export const HOOKS_DIR = 'hooks';
export const LOCKFILE_NAME = 'zepher-lock.yaml';

export const WATERMARK_HEADER = '<!-- AUTO-GENERATED BY ZEPHER — DO NOT EDIT DIRECTLY -->';
export const WATERMARK_FOOTER = '<!-- To modify, update rules in .zepher/rules/ or run `zepher rule add` -->';
