import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { WATERMARK_HEADER, WATERMARK_FOOTER } from './constants.js';

export function calculateChecksum(content: string): string {
  return crypto.createHash('sha256').update(content.trim()).digest('hex').slice(0, 12);
}

export function generateWatermark(checksum: string): string {
  const timestamp = new Date().toISOString();
  return `${WATERMARK_HEADER}\n<!-- Last synced: ${timestamp} | Checksum: ${checksum} -->\n${WATERMARK_FOOTER}\n\n`;
}

export function isWatermarked(filePath: string): boolean {
  if (!fs.existsSync(filePath)) return false;
  const content = fs.readFileSync(filePath, 'utf-8');
  return content.includes(WATERMARK_HEADER);
}

export interface WriteCheckResult {
  canWrite: boolean;
  reason?: string;
  isExisting: boolean;
  isWatermarked: boolean;
}

export function checkFileWriteSafety(filePath: string, force: boolean = false): WriteCheckResult {
  if (!fs.existsSync(filePath)) {
    return { canWrite: true, isExisting: false, isWatermarked: false };
  }

  const watermarked = isWatermarked(filePath);
  if (force) {
    return { canWrite: true, isExisting: true, isWatermarked: watermarked };
  }

  if (!watermarked) {
    return {
      canWrite: false,
      reason: `File "${path.basename(filePath)}" exists and was not generated by Zepher. Use "zepher import" to import it or "--force" to overwrite.`,
      isExisting: true,
      isWatermarked: false
    };
  }

  return { canWrite: true, isExisting: true, isWatermarked: true };
}

export function safeWriteFile(filePath: string, content: string, force: boolean = false): { success: boolean; message: string } {
  const safety = checkFileWriteSafety(filePath, force);
  if (!safety.canWrite) {
    return { success: false, message: safety.reason || 'Safety check failed.' };
  }

  const checksum = calculateChecksum(content);
  const finalContent = generateWatermark(checksum) + content;

  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(filePath, finalContent, 'utf-8');
  return { success: true, message: `Successfully wrote ${path.basename(filePath)}` };
}

export function deepMergeJson(target: Record<string, any>, patch: Record<string, any>): Record<string, any> {
  const output = { ...target };
  for (const key of Object.keys(patch)) {
    if (patch[key] !== null && typeof patch[key] === 'object' && !Array.isArray(patch[key])) {
      if (key in target && typeof target[key] === 'object' && !Array.isArray(target[key])) {
        output[key] = deepMergeJson(target[key], patch[key]);
      } else {
        output[key] = patch[key];
      }
    } else {
      output[key] = patch[key];
    }
  }
  return output;
}

export function safeMergeJsonFile(filePath: string, patch: Record<string, any>): { success: boolean; message: string } {
  let current: Record<string, any> = {};
  if (fs.existsSync(filePath)) {
    try {
      current = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
    } catch {
      current = {};
    }
  }

  const merged = deepMergeJson(current, patch);
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(filePath, JSON.stringify(merged, null, 2) + '\n', 'utf-8');
  return { success: true, message: `Merged patch into ${path.basename(filePath)}` };
}
