import { describe, it, expect } from 'vitest';
import { calculateChecksum, generateWatermark } from './safety.js';

describe('Safety and Checksum System', () => {
  it('calculates deterministic checksum', () => {
    const text = 'Hello Zepher';
    const sum1 = calculateChecksum(text);
    const sum2 = calculateChecksum(text);
    expect(sum1).toBe(sum2);
    expect(sum1.length).toBe(12);
  });

  it('generates proper watermark', () => {
    const watermark = generateWatermark('abc123456789');
    expect(watermark).toContain('AUTO-GENERATED BY ZEPHER');
    expect(watermark).toContain('Checksum: abc123456789');
  });
});
